### PR TITLE
feat: sort projects in project view

### LINKED ISSUE #1111: List Projects in the Projects View in Alphabetical Order.
While there is now a way to **[filter projects in the project view](https://github.com/nrwl/nx-console/pull/1050)**, I think a lot of the pain of searching through the project view, particularly in large monorepos, could be alleviated by simply listing the projects in alphabetical order.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This commit adds sorting applied to projects found in workspace
configuration, before content is returned to the UI. Entries are sorted
using current environment locale settings.

- implementation
- tests

Thanks!

Closes #1111

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
wait, I'm surprised it's not reflected in panel view. I'll mark this as WIP. Any clue where to look? thx!

**Comment by Cammisuli** [comment]
If you want to sort the projects in the Projects view, then you'll have to manipulate the `getChildren` function in here:
https://github.com/nrwl/nx-console/blob/7ad5f60cdba5a0f766592aed5b718ba82c3e0881/libs/vscode/nx-project-view/src/lib/nx-project-tree-provider.ts#L88-L96

**Comment by peterblazejewicz** [comment]
@Cammisuli thx! Let me check this.

**Comment by peterblazejewicz** [comment]
This was probably due to staled branch bits or something. I can see it works as expected. Projects are sorted,
when project name is changed in workspace config file, this is instantly reflected in projects panel:
this is the same project renamed couple of times:

image
image
image

@Cammisuli can you please clone this and run, just to confirm.
I'll review outcome of pointed method in provider (via test case), TBC

**Comment by Cammisuli** [comment]
oh ya, the original implementation was working 😅 Once you're ready, we can merge this in and release it

**Comment by peterblazejewicz** [comment]
> oh ya, the original implementation was working 😅 Once you're ready, we can merge this in and release it

Done, I've hardened the tests mocks for file system checks, they were returning kind of random outcome, now that's correctted.

**Review by Cammisuli — APPROVED** [review]
Thank you! It's going to be coming out in the next release very soon 😄

**Pull request merged**
