### PR TITLE
feat: show generate ui from explorer context menu

### PR DESCRIPTION
**Pull request by glenngr**
nx generate ui can be shown by right clicking in explorer context menu
the path you click on will be used as a value for the "path" option
the "project" option will also be updated based on the path 

See discussion in #974, issues listed there has been solved. 

I have only tested on windows so far. Should we make sure it works in mac and linux as well?

Any more changes or suggestions?

### CODE REVIEW

**Comment by isaacplmann** [comment]
I'll test on mac.

**Comment by isaacplmann** [comment]
This looks great.  After trying this out with an assortment of schematics, I think you should also auto-populate a `directory` field in a schematic with the same value as `path`.  Once that's in place, I'll merge it in.

**Comment by glenngr** [comment]
Just set "directory" to the same value as "path", like in my latest force-push update?

**Comment by glenngr** [comment]
Should the README or other documentation be updated as well? Maybe how to disable the menu item through the settings?

**Comment by isaacplmann** [comment]
I'm sorry, I made a bad suggestion.  Apparently all the `directory` fields don't work the same way as the `path` fields.  The `directory` fields want a path relative to the project root, not the workspace root.

I think we should revert those changes and potentially revisit that in a separate PR.  There are a lot of weird edge cases to the directory field.

So if you switch it back to just populating `path` and `project`, I'll merge this in.

**Comment by glenngr** [comment]
Ok, no problem. I have reverted the change now.

**Comment by isaacplmann** [comment]
Thanks! I'll test and merge this on Monday

**Comment by isaacplmann** [comment]
Thanks!  This is a great feature

**Comment by glenngr** [comment]
@isaacplmann when will the new version of the vscode plugin be released?

**Pull request merged**
