### PR TITLE
feat: go to executor definition

### PR DESCRIPTION
**Pull request by MJez29**
Implements the Go To Definition functionality requested in https://github.com/nrwl/nx-console/issues/1936 for VSCode

### Changes

1. Refactored `CollectionInfo` to a union type for better typing
2. Duplicated the `hover` package and changed references to `definition`
3. Implemented the `goToDefinition` capability 

### Testing

Verified that it worked in the nx repo and my own repo

https://github.com/nrwl/nx-console/assets/20645805/8c814979-3f9e-4b3c-ac42-8d0165f66c49

### CODE REVIEW

**Comment by MaxKless** [comment]
Sorry for the slow communication. This looks awesome!! I really appreciate the contribution, especially since it looks pretty involved.
I'll set some time aside to review it soon.
Thanks!

**Review by MaxKless — CHANGES_REQUESTED** [review]
First of all, awesome PR. Functionality is great, code reads well and you even improved some types. So thanks.

I tested it and it works well across package managers & local plugins 👍 

The only thing we need to make sure is that JetBrains support works. Do you have access to IntelliJ or should I look into it?

**Comment by MaxKless** [comment]
I'd like to add it right away - I didn't find any issues on a superficial look but when we edit the types passed between nxls & ide, stuff can break. 

The nxls-related code in jetbrains is in `apps/intellij/src/main/kotlin/dev.nx.console/nxls`. In `NxlsWrapper.getInitParams`, you can see the definition of what LSP features are used. 
We use `lsp4j` under the hood so definitely look at the docs there: https://github.com/eclipse-lsp4j/lsp4j

Let me know if I can help out with anything else :)

**Comment by MJez29** [comment]
I gave it a try but it kept trying to open IntelliJ Ultimate and prompting for a license which I don't have. Is there a way to have it use the Community Edition?

**Comment by MaxKless** [comment]
ah, too bad. Because Nx Console uses the proprietary javascript plugins by JetBrains under the hood, you can't use it with IntelliJ Community. 
In that case I will have a look at adding intellij support :)

**Comment by MJez29** [comment]
Hey @MaxKless, just following up here, have you had a chance to try out my change on IntelliJ?

**Comment by MaxKless** [comment]
Sorry @MJez29 for the long wait. We're pushing out a big release so this has fallen under the radar. I will just merge this without IntelliJ support but have to go over it again first and make sure it becomes green. 
Could you rebase on master? :)

**Review by MaxKless — APPROVED** [review]

**Comment by MaxKless** [comment]
thanks for the awesome contribution @MJez29!!

**Pull request merged**
